import {
  propertyA,
  propertyB,
  propertyC,
  propertyD,
  propertyE,
  propertyF,
  propertyG,
  propertyH,
  propertyI,
} from "@/assets";

const property = [
  {
    image: propertyA,
    name: "Real House Luxury Villa",
    id: 0,
    location: "Victoria Island, Lagos",
    bedroom: "6 Bedrooms",
    bathroom: "3 Bathrooms",
    price: "3340000000",
  },
  {
    image: propertyB,
    name:"Exquisite Haven Villa",
    id: 1,
    location: "Festac, Lagos",
    bedroom: "5 Bedrooms",
    bathroom: "3 Bathrooms",
    price: "4000000",
  },
  {
    image: propertyC,
    id: 2,
    name: "Luxe Palatial Villa",
    location: "Gbagada, Lagos",
    bedroom: "7 Bedrooms",
    bathroom: "3 Bathrooms",
    price: "5350000000",
  },
  {
    image: propertyD,
    id: 3,
    name: "Harmony Luxury Villa",
    location: "Mushin, Lagos",
    bedroom: "4 Bedrooms",
    bathroom: "3 Bathrooms",
    price: "4000000",
  },
  {
    image: propertyE,
    name: "Real House Luxury Villa",
    id: 4,
    location: "Victoria Island, Lagos",
    bedroom: "6 Bedrooms",
    bathroom: "3 Bathrooms",
    price: "350000000",
  },
  {
    image: propertyF,
    name: "Real House Luxury Villa",
    id: 5,
    location: "Lekki-Ajah, Lagos",
    bedroom: "6 Bedrooms",
    bathroom: "3 Bathrooms",
    price: "4200000",
  },
  {
    image: propertyG,
    name: "Infinite Bliss Villa",
    id: 6,
    location: "Ishiagu, Enugu",
    bedroom: "5 Bedrooms",
    bathroom: "3 Bathrooms",
    price: "2350000000",
  },
  {
    image: propertyH,
    name: "Real House Luxury Villa",
    id: 7,
    location: "Works Layout, Owerri",
    bedroom: "8 Bedrooms",
    bathroom: "6 Bathrooms",
    price: "3350000",
  },
  {
    image: propertyI,
    name: "Real House Luxury Villa",
    id: 8,
    location: "Ikeja, Lagos",
    bedroom: "6 Bedrooms",
    bathroom: "6 Bathrooms",
    price: "600000000",
  },
];

export { property };
